//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worldskills
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public string Number { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public string Product { get; set; }
        public string Supplier_login { get; set; }
        public string Supplier_password { get; set; }
        public string Manager_login { get; set; }
        public string Manager_password { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> End_date { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
